@startuml
' WebSocket 客戶端線上狀態管理

autonumber

client -> service: 透過 WebSocket 私信發送心跳請求
service --> client: 返回接收到心跳資訊
service -> redis: 快取記錄下最後一次訪問時間
service -> rabbitmq: 發送延遲訊息（延遲時間大於心跳時間）
rabbitmq --> service: 延遲訊息到時間會發送訊息讓伺服器檢查快取中客戶端最後一次記錄時間超時再記錄到資料庫：最後一次心跳時間，客戶端狀態為未連接。

client -> service: 如果長時間接收到伺服器發送的心跳確認資訊，發請求連接
@enduml